shoppingnet/shopping/urls.py
from django.conf.urls import url
from shopping.views import HomePage, ShopDetail, GoodsDetail, UserOrder, UserShoppingCart, ShopDetail, ManageShop, ManageGoods, AddGoods
from shopping.views import CompleteUserInfo, CompleteShopInfo, ShopOrder, ShopOrderFormDetail
from shopping.views import InfoView
from shopping import views

urlpatterns = [
	# 商店列表，购物网站的首页
	# ex: /shopping/
    url(r'^$', views.HomePage, name = "index"),
    # 某个商店，主要内容为购物进入某店时，商品列表
    # ex: /shopping/5/
    url(r'^(?P<shop_id>[0-9]+)/$', views.ShopDetail),
    #
    #完善商店信息
    url(r'^shop_info/$', views.CompleteShopInfo),
    #
    #完善商品信息
    url(r'^user_info/$', views.CompleteUserInfo),
    #
    # 某个商店，主要为店主直接修改某些商品信息
    url(r'^shop/(?P<shop_id>[0-9]+)/$', views.ManageShop),
    # 某个商品的详细信息
    # ex: shopping/goods/2
    url(r'^goods/(?P<goods_id>[0-9]+)/$', views.GoodsDetail),
    #
    #
    url(r'^shop/goods/(?P<goods_id>[0-9]+)/$', views.ManageGoods),
    # 
    # 
    url(r'^shop/add_goods/$', views.AddGoods),
    # 显示用户历史记录的页面, 里面可以评分...
    # ex: /user/5/order
    url(r'^user_order/$', views.UserOrder),

    url(r'^user_order/(?P<order_id>[0-9]+)/$', views.UserOrderFormDetail),
    # 显示用户购物车的页面
    # ex: /user/5/cart
    url(r'^cart/$', views.UserShoppingCart),

    url(r'^cart/(?P<order_id>[0-9]+)/$', views.UserShoppingCartDetail),

    url(r'^shop_order/$', views.ShopOrder),

    url(r'^shop_order/(?P<order_id>[0-9]+)/$', views.ShopOrderFormDetail),

    url(r'^info_view/$', views.InfoView, name = "info_view"),
]

shoppingnet/shoppingnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from shopping.forms import MyCustomUserForm
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
	
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$',
        RegistrationView.as_view(
            form_class=MyCustomUserForm
        ),
        name='registration_register',
    ),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'', include('shopping.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppingnet/shopping/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from datetime import datetime
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Shop(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='')
	name = models.CharField(max_length = 30, default="")
	description = models.TextField(max_length = 300)
	sold_number = models.IntegerField(default = 0)
	category = models.CharField(max_length = 20, default="")
	tele = models.CharField(max_length = 20, default="")
	class Meta:
		ordering = ["-name"]

	def __str__(self):
		return self.name

class Customer(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, default = '')
	head_img = models.ImageField(upload_to = 'img', null=True, blank=True, default="img/no_image.png")
	name = models.CharField(max_length = 20, default="")
	address = models.CharField(max_length = 200, default="")
	sex = models.CharField(max_length = 10, default="")
	self_intro = models.TextField(max_length = 300)
	tele = models.CharField(max_length = 20, default="")
	def __str__(self):
		return self.name

class Goods(models.Model):
	image = models.ImageField(upload_to = 'img', null=True, blank=True, default="img/no_img.jpg")
	shop = models.ForeignKey(Shop, on_delete = models.CASCADE)
	#以下商品信息，店主无法直接修改
	name = models.CharField(max_length = 30)
	category = models.CharField(max_length = 20, default="")
	description = models.TextField(max_length = 300)
	price = models.IntegerField(default = 0)
	number = models.IntegerField(default = 0)
	#以下信息，店主无法修改
	sold_number = models.IntegerField(default = 0)
	rating = models.IntegerField(default = 0)
	rating_number = models.IntegerField(default = 0)
	#
	rating_total = models.IntegerField(default = 0)

	def __str__(self):
		return str(self.name)+'+'+str(self.id)

class OrderForm(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	goods = models.ForeignKey(Goods, on_delete = models.CASCADE)
	total_price = models.IntegerField(default = 0)
	number = models.IntegerField(default = 0)
	message = models.CharField(max_length = 200, default="")
	address = models.TextField(max_length = 300)
	tele = models.CharField(max_length = 20, default="")
	#-1 表示是购物车
	#1	下单 
	#2	确认
	#3	发货
	#4	收货
	#5  完成
	status = models.IntegerField(default = 0)

	def __str__(self):
		return self.user.customer.name

class Search(models.Model):
	OBJECTNAME_CHOICE = (
		('商店','商店'),
		('商品','商品'),
	)
	FIELDNAME_CHOICE = (
		('名称','名称'),
		('类别','类别'),
	)

	content = models.CharField(max_length = 20, default="")
	object_name = models.CharField(max_length = 4, choices = OBJECTNAME_CHOICE, default = '商品')
	field_name = models.CharField(max_length = 4, choices = FIELDNAME_CHOICE, default = '名称')

class Comment(models.Model):
	order =  models.OneToOneField(OrderForm, on_delete = models.CASCADE, default='')
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, default='')
	goods = models.ForeignKey(Goods, on_delete = models.CASCADE, default='')
	rating = models.IntegerField(default = 0)
	content = models.TextField(max_length = 300)
	date = models.DateTimeField(default = datetime.now)
	isReplied = models.BooleanField(default = 'False')

	def __str__(self):
		return self.content

class Reply(models.Model):
	comment = models.ForeignKey(Comment, on_delete = models.CASCADE, default='')
	rating = models.IntegerField(default = 0)
	content = models.TextField(max_length = 300)
	date = models.DateTimeField(default = datetime.now)

	def __str__(self):
		return self.content

shoppingnet/shopping/forms.py
from django import forms
from django.forms import ModelForm
from registration.forms import RegistrationForm
from customauth.models import MyUser
from shopping.models import Goods, Shop, Customer, OrderForm, Comment, Search, Reply
from django.utils.translation import ugettext_lazy as _

class MyCustomUserForm(RegistrationForm):
    class Meta:
        model = MyUser
        fields = ['email', 'is_shop']

class GoodsForm(forms.Form):
	number = forms.IntegerField()

class ManageGoodsForm(forms.ModelForm):
	class Meta:
		model = Goods
		exclude = ['shop', 'rating','rating_number', 'rating_total', 'sold_number']
		labels = {
			'name':_("名称"),
			'category':_("类别"),
			'description':_("描述"),
			'price':_("价格"),
			'number':_("数量"),
		}

class ShopInfoForm(forms.ModelForm):
	class Meta:
		model = Shop
		exclude = ['user','sold']
		labels = {
			'name':_("名称"),
			'category':_("类别"),
			'tele':_("联系方式"),
			'description':_("描述"),
		}

class CustomerForm(forms.ModelForm):
	class Meta:
		model = Customer
		exclude = ['user',]
		labels = {
			'head_img':_("头像"),
			'name':_("姓名"),
			'sex':_("性别"),
			'tele':_("联系方式"),
			'address':_("地址"),
			'self_intro':_("个人简介"),	
		}

class UserOrderForm(forms.ModelForm):
	class Meta:
		model = OrderForm
		fields = ['number', 'message', 'tele', 'address']
		labels = {
			'number':_("数量"),
			'message':_("附加信息"),
			'tele':_("联系方式"),
			'address':_("收货地址"),
		}

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['rating', 'content']
		labels = {
			'rating':_("评分"),
			'content':_("评论"),
		}

class ReplyForm(forms.ModelForm):
	class Meta:
		model = Reply
		fields = ['rating', 'content']
		labels = {
			'rating':_("评分"),
			'content':_("回复内容"),
		}

class SearchForm(forms.ModelForm):
	class Meta:
		model = Search
		fields = ['content', 'field_name', 'object_name']

shoppingnet/shopping/views.py
from shopping.forms import GoodsForm, ManageGoodsForm, ShopInfoForm, CustomerForm, UserOrderForm, SearchForm, CommentForm, ReplyForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from shopping.models import Goods, Shop, OrderForm, Comment, Customer, Reply


def HomePage(request):
	if request.user.is_authenticated() and request.user.is_complete == False and request.user.is_shop == True:
		return HttpResponseRedirect('/shop_info/')

	if request.user.is_authenticated() and request.user.is_complete == False and request.user.is_shop == False:
		return HttpResponseRedirect('/user_info/')

	if request.user.is_authenticated() and request.user.is_shop == True:
		return HttpResponseRedirect('/shop/' + str(request.user.shop.id))

	if request.method == "POST":
		form = SearchForm(request.POST)
		if form.is_valid():
			temp = form.save(commit=False)
			if temp.object_name == '商品' and temp.field_name == '名称':
				goods_list = Goods.objects.filter(name__contains=temp.content)
				return GoodsSearchResult(request, goods_list)
			if temp.object_name == '商品' and temp.field_name == '类别':
				goods_list = Goods.objects.filter(category__contains=temp.content)
				return GoodsSearchResult(request, goods_list)
			if temp.object_name == '商店' and temp.field_name == '名称':
				shop_list = Shop.objects.filter(name__contains=temp.content)
				return ShopSearchResult(request, shop_list)
			if temp.object_name == '商店' and temp.field_name == '类别':
				shop_list = Shop.objects.filter(category__contains=temp.content)
				return ShopSearchResult(request, shop_list)
	else:
		form = SearchForm()
	
	index_shop_List = Shop.objects.order_by("id")
	context = {
		'index_shop_List' : index_shop_List,
		'form': form,
		'user': request.user,
	}
	return render(request, 'shopping/index.html', context)

def GoodsSearchResult(request, goods_list):
	if len(goods_list) == 0:
		return render(request, 'shopping/search_not_found.html')
	context = {
		'goods_list' : goods_list,
		'user' : request.user,
	}
	return render(request, 'shopping/search_goods.html', context)

def ShopSearchResult(request, shop_list):
	if len(shop_list) == 0:
		return render(request, 'shopping/search_not_found.html')
	context = {
		'shop_list' : shop_list,
	}
	return render(request, 'shopping/search_shop.html', context)

def CompleteUserInfo(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	if request.method == "POST":
		if request.user.is_complete == True:
			form = CustomerForm(request.POST, request.FILES, instance=request.user.customer)
		else:
			form = CustomerForm(request.POST, request.FILES)
		if form.is_valid():
			if 'submit' in request.POST:
				temp = Customer()
				temp = form.save(commit=False)
				request.user.is_complete = True
				temp.user = request.user
				temp.save()
				request.user.save()
				return HttpResponseRedirect('/')
	else:
		if request.user.is_complete == True:
			form = CustomerForm(instance=request.user.customer)
		else:
			form = CustomerForm()
	context = {
		'form': form,
		'user': request.user,
	}
	return render(request, 'shopping/user_info.html', context)

def CompleteShopInfo(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	if request.method == "POST":
		if request.user.is_complete:
			form = ShopInfoForm(request.POST, instance=request.user.shop)
		else:
			form = ShopInfoForm(request.POST)
		if form.is_valid():
			if 'submit' in request.POST:
				temp = Shop()
				temp = form.save(commit=False)
				request.user.is_complete = True
				temp.user = request.user
				temp.save()
				request.user.save()
				return HttpResponseRedirect('/')
	else:
		if request.user.is_complete:
			form = ShopInfoForm(instance=request.user.shop)
		else:
			form = ShopInfoForm()
	context = {
		'form': form,
	}
	return render(request, 'shopping/shop_info.html', context)


def ShopDetail(request, shop_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	shop = Shop.objects.get(pk = shop_id)
	context = {
		'shop' : shop,
	}
	return render(request, 'shopping/user_goods_list.html', context)

def ManageShop(request, shop_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	shop = Shop.objects.get(pk = shop_id)
	context = {
		'shop' : shop,
	}
	return render(request, 'shopping/shop_goods_list.html', context)

def GoodsDetail(request, goods_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	goods = Goods.objects.get(pk = goods_id)
	if request.method == 'POST':
		form = UserOrderForm(request.POST)
		if form.is_valid():
			if 'buy' in request.POST:
				of = OrderForm()
				of = form.save(commit=False)
				if of.number > goods.number:
					return HttpResponseRedirect('/')
				of.goods = goods
				goods.sold_number += of.number
				goods.number -= of.number
				goods.save()
				of.user = request.user
				of.total_price = of.number * goods.price
				of.status = 1
				of.save()
				return HttpResponseRedirect('/user_order/')
			if 'collect' in request.POST:
				of = OrderForm()
				of = form.save(commit=False)
				if of.number > goods.number:
					return HttpResponseRedirect('/')
				of.goods = goods
				of.user = request.user
				of.status = -1
				of.save()
				return HttpResponseRedirect('/cart/')
			if 'viewComment' in request.POST:
				return HttpResponseRedirect('/goods')
	else:
		form = UserOrderForm()

	context = {
        'goods': goods,
        'form' : form,
    }
	return render(request, 'shopping/goods.html', context)

def ManageGoods(request, goods_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	goods = Goods.objects.get(pk = goods_id)
	message = '请在表单中修改'

	if request.method == 'POST':
		form = ManageGoodsForm(request.POST, request.FILES, instance = goods)
		if form.is_valid():
			if 'delete' in request.POST:
				shop_id = goods.shop.id
				goods.delete()
				return HttpResponseRedirect('/shop/'+str(shop_id)+'/')
			if 'save' in request.POST:

				form.save()
				form = ManageGoodsForm(instance= goods)

				message = '成功修改！'
	else:
		form = ManageGoodsForm(instance = goods)

	context = {
        'goods': goods,
        'form' : form,
        'message' : message, 
    }
	return render(request, 'shopping/shop_goods.html', context)

def AddGoods(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	if request.method == "POST":
		form = ManageGoodsForm(request.POST, request.FILES)
		if form.is_valid():
			if 'submit' in request.POST:
				temp = Goods()
				temp = form.save(commit=False)
				temp.shop = request.user.shop
				temp.rating = 0
				temp.rating_number = 0
				temp.rating_total = 0
				temp.sold_number = 0
				temp.save()
				return HttpResponseRedirect('/')
	else:
		form = ManageGoodsForm()
	context = {
		'form': form,
	}
	return render(request, "shopping/shop_add_goods.html", context)

def UserShoppingCart(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	user_cart = request.user.orderform_set.all().filter(status = -1)
	if request.method == "POST":
		if 'buy' in request.POST:
			for order in user_cart:
				order.goods.sold_number += order.number
				order.goods.number -= order.number
				order.total_price = order.number * order.goods.price
				order.status = 1
				order.save()
				order.goods.save()
	user_cart = request.user.orderform_set.all().filter(status = -1)
	context = {
		"user_cart" : user_cart,
	}
	return render(request, "shopping/user_cart_list.html", context)

def UserShoppingCartDetail(request, order_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	order = OrderForm.objects.get(pk = order_id)
	if request.method == "POST":
		if 'buy' in request.POST:
			order.status = 1
			order.goods.sold_number += order.number
			order.goods.number -= order.number
			order.total_price = order.number * order.goods.price
			order.goods.save()
			order.save()
			return HttpResponseRedirect('/order')
		if 'delete' in request.POST:
			order.delete()
			return HttpResponseRedirect('/cart')
	context = {
		"order" : order
	}

	return render(request, 'shopping/cart.html', context)

def UserOrder(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	user_order = request.user.orderform_set.all().exclude(status = -1)
	context = {
		"user_order" : user_order,
	}
	return render(request, "shopping/user_order_list.html", context)

def UserOrderFormDetail(request, order_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	order = OrderForm.objects.get(pk = order_id)
	com = CommentForm(request.POST)
	message = "请进行操作"
	if request.method == "POST":
		if 'delete' in request.POST:
			order.delete()
			return HttpResponseRedirect('/user_order')
		if 'cancle' in request.POST:
			order.status = 0
			return HttpResponseRedirect('/user_order')
		if 'confirm' in request.POST:
			order.status = 4
			order.save()
			message = '确认收货成功'
		if 'comment' in request.POST:
			comm = Comment()
			comm = com.save(commit=False)
			comm.user = request.user
			comm.order = order
			comm.goods = order.goods
			comm.isReplied = False
			if comm.rating > 5:#分数大于5时，取5
				comm.rating = 5
			if comm.rating < 0:#分数小于0时，取0
				comm.rating = 0
			order.goods.rating_total += comm.rating
			order.goods.rating_number += 1
			order.goods.rating = order.goods.rating_total / order.goods.rating_number
			order.goods.save()
			order.status = 5
			order.save()
			comm.save()
			context={
				'goods': order.goods,
			}
			return render(request, 'shopping/goods.html', context)
	context = {
		"order" : order,
		'message' : message,
		'comment': com, 
	}
	return render(request, 'shopping/user_order.html', context)

def ShopOrder(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	shop = request.user.shop
	context = {
		'shop' : shop,
	}

shoppingnet/shopping/templates/shopping/cart.html
{% extends "base.html" %}
{% block content %}

<h2>购物车详情</h2>
<section>
	<img src="{{order.goods.image.url}}" width="100px" height="100px">
	<p>商品: {{order.goods.name}} </p>
	<p>店铺: {{order.goods.shop.name}} </p>
	<p>数量: {{order.number}} </p>
	<p>联系方式: {{order.tele}} </p>
	<p>地址: {{order.address}}</p>
	
	<form method="POST">
	{% csrf_token %}
		<button type="submit" name = "buy">buy</button>
		<button type="submit" name = "delete">delete</button>
	</form>
</section>
{% endblock %}

shoppingnet/shopping/templates/shopping/comment.html
{% extends "base.html" %}
{% block content %}

{% for co in goods.comment_set.all%}
	<img src="{{co.user.customer.head_img.url}}" width="100px" height="100px">
	<p>用户: {{co.user.customer.name}}</p>
	<p>评分: {{co.rating}}</p>
	<p>评论内容: {{co.content}}</p>
	<p>日期: {{co.date}}</p>
	{% if co.isRpeplied %}
		<br><p>商家回复: </p>
		<p>评分: {{co.reply.rating}}</p>
		<p>回复内容: {{co.reply.content}}</p>
		<p>日期: {{co.reply.date}}</p>
	{% endif %}
	<hr />
{% endfor %}

{% endblock %}

shoppingnet/shopping/templates/shopping/info_view.html
<!--7/25 by Dixon-->
{% extends "base.html" %}
{% block content %}

{% if user.is_shop %}
	<p>name: {{user.shop.name}}</p><br>
	<p>email: {{user.email}}</p><br>
	<p>category: {{user.shop.category}}</p><br>
	<p>address: {{user.shop.address}}</p><br>
	<p>description: {{user.shop.description}}</p><br>
{% else %}
	<p>headImg: </p><img src="{{user.customer.head_img.url}}" width="100" height="100">
	<p>name: {{user.customer.name}}</p>
	<p>email: {{user.email}}</p>
	<p>sex: {{user.customer.sex}}</p>
	<p>tel: {{user.customer.tel}}</p>
	<p>address: {{user.customer.address}}</p>
	<p>selfIntro: {{user.customer.self_intro}}</p>
{% endif %}
<hr />
{% csrf_token %}
	<button type="submit" name = "changeInfo">修改信息</button>
{% endblock %}
<!--7/25 by Dixon done-->

shoppingnet/shopping/templates/shopping/search_goods.html
{% extends "base.html" %}
{% block content %}
<h2>商品搜索结果</h2>

<ul>
	{% for goods in goods_list %}
		<section>
		<li><img src="{{goods.image.url}}" width="100px" height="100px">
		<p> 名称 {{goods.name}} </p></li>
		<ul>
			<li> 类别 {{goods.category }} </li>
			<li> 描述 {{goods.description}} </li>
			<li> <a href="/goods/{{goods.id}}"> 更多信息 </a> </li>
		</ul>
		</section>
		<hr />
	{% endfor %}
</ul>

{% endblock %}

shoppingnet/shopping/templates/shopping/search_not_found.html
{% extends "base.html" %}
{% block content %}
<h2>NOT FOUND</h2>
{% endblock %}

shoppingnet/shopping/templates/shopping/search_shop.html
{% extends "base.html" %}
{% block content %}
<h2>商品搜索结果</h2>

<ul>
	{% for shop in shop_list %}
	<section>
		<p> 名称 {{shop.name}} </p>
		<ul>
			<li> 类别 {{shop.category }} </li>
			<li> 描述 {{shop.description}} </li>
			<li><a href="/{{shop.id}}"> 更多信息 </a></li>
		</ul>
	</section>
	<hr />
	{% endfor %}
</ul>
{% endblock %}

shoppingnet/shopping/templates/shopping/shop_add_goods.html
{% extends "base.html" %}
{% block content %}

<h2>店铺增添商品</h2>

<hr>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<section>
	{{ form.as_p }}
	<button type="submit" name = "submit">提交</button>
</section>
</form>
{% endblock %}

shoppingnet/shopping/templates/shopping/shop_goods_list.html
{% extends "base.html" %}
{% block content %}
<h2>商店管理界面</h2>
<h2>No. {{shop.id}} </h2>

<h3>店名 {{shop.name}} </h3>
<h3>类别 {{shop.category}} </h3>
<h3>联系方式 {{shop.tele}}
<h3>描述 {{shop.description}} </h3>

<ul>
	{% for goods in shop.goods_set.all %}
	<section>
		<li>
		<img src="{{goods.image.url}}" width="100px" height="100px">
		<a href="/shop/goods/{{goods.id}}/">
			{{goods.name}}
		</a></li>
	</section>
	<hr />
	{% endfor %}
</ul>
{% endblock %}

{%block footer%}
	<a href="/shop/add_goods/">添加商品</a>
	<a href="/shop_order/">订单管理</a>
{% endblock %}

shoppingnet/shopping/templates/shopping/shop_manage_goods.html
{% extends "base.html" %}
{% block content %}

<h2>店铺商品管理</h2>

<hr>
<form method="POST">
{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" name = "delete">删除</button>
	<button type="submit" name = "save">保存</button>
</form>
{% endblock %}

shoppingnet/shopping/templates/shopping/shop_order.html
{% extends "base.html" %}
{% block content %}

<h2>店铺订单管理</h2>
<section>
	<p>商品: {{order.goods.name}} </p>
	<p>店铺: {{order.goods.shop.name}} </p>
	<p>数量: {{order.number}} </p>
	<p>单价: {{order.goods.price}}</p>
	<p>总价: {{order.total_price}}</p>
	{% if order.status == 1 %}
		<p>状态: 已下单 </p>
	{% elif order.status == 2 %}
		<p>状态: 商家已确认 </p>
	{% elif order.status == 3 %}
		<p>状态: 商家已发货 </p>
	{% elif order.status == 4 %}
		<p>状态: 已确认收货 </p>
	{% elif order.status == 5 %}
		<p>状态: 已完成 </p>
	{% else %}
		<p>状态: 已取消 </p>
	{% endif %}
	<p>买家: {{order.user.customer.name}} </p>
	<p>联系方式: {{order.tele}} </p>
	<p>地址: {{order.address}}</p>
	{% if order.status == 5 %}
		<p>用户评分: {{order.comment.rating}}</p>
		<p>用户评论: {{order.comment.content}}</p>
		<p> {{order.comment.date}}</p>
		{% if order.comment.isReplied %}
			{% for reply in order.comment.reply_set.all %}
			<p>回复评分: {{reply.rating}}</p>
			<p>回复评论: {{reply.content}}</p>
			<p> {{reply.date}}</p>
			{% endfor %}
		{% endif %}
	{% endif %}
</section>
<hr>
<form method="POST">
<section>
{% csrf_token %}
	{% if order.status == 1 %}
		<button type="submit" name = "confirm">确定订单</button>
	{% endif %}
	{% if order.status == 2 %}
		<button type="submit" name = "delivery">已发货</button>
	{% endif %}
	<br>
</form>
<form method="POST">
{% csrf_token %}
{% if order.status == 5 %}
	{% if not order.comment.isReplied %}
		<p>回复评论 </p>
		{{ replyForm.as_p }}
		<button type="submit" name = "reply">回复</button>
	{% endif %}
	<p>注: 分数为5分制，大于5自动取5分，小于0自动取0分 </p>
{% endif %}
</section>
</form>

{% endblock %}

shoppingnet/shopping/templates/shopping/shop_order_list.html
{% extends "base.html" %}
{% block content %}

<h2>订单管理</h2>
<h3>以下是订单列表</h3>

<ul>
	{% for goods in shop.goods_set.all %}
	<li>
		{% for order in goods.orderform_set.all %}
		<section>
		<li>
			<img src="{{goods.image.url}}" width="100px" height="100px">
			<p>商品 {{goods.name}}</p>
			<p>数量 {{order.number}} </p>
			<p>单价: {{order.goods.price}}</p>
			<p>总价: {{order.total_price}}</p>
			{% if order.status == 1 %}
				<p>状态: 已下单 </p>
			{% elif order.status == 2 %}
				<p>状态: 商家已确认 </p>
			{% elif order.status == 3 %}
				<p>状态: 商家已发货 </p>
			{% elif order.status == 4 %}
				<p>状态: 已确认收货 </p>
			{% elif order.status == 5 %}
				<p>状态: 已完成 </p>
			{% else %}
				<p>状态: 已取消 </p>
			{% endif %}
			<a href= "{{order.id}}">更多信息</a>
		</li>
		</section>
		<hr />
		{% endfor %}
	</li>
	{% endfor %}
</ul>

{% endblock %}

shoppingnet/shopping/templates/shopping/user_cart.html
{% extends "base.html" %}
{% block content %}

<h2>the shopping cart of {{user_cart.username}}</h2>

<ul>
	{% for cart in user_cart.shoppingcart_set.all %}
	<li>
		<a href= "{{cart.id}} " > goods: {{cart.goods.name}} </a>
		<p>number: {{cart.number}} </p>
		<p>shop: {{cart.goods.shop.name}} </p>
	</li>
	{% endfor %}
</ul>

{% endblock %}

shoppingnet/shopping/templates/shopping/user_goods_list.html
{% extends "base.html" %}
{% block content %}
<h2>{{ shop.name }} 的商品列表 </h2>

<ul>
	{% for goods in shop.goods_set.all %}
	<section>
		<li>
		<img src="{{goods.image.url}}" width="100px" height="100px">
		<a href="/goods/{{goods.id}}/">
			{{goods.name}}
		</a></li>
	</section>
	<hr />
	{% endfor %}
</ul>

{% endblock %}

shoppingnet/shopping/templates/shopping/user_info.html
{% extends "base.html" %}
{% block content %}

<h2>用户信息完善</h2>

<hr>
<section>
<form method="POST"  enctype="multipart/form-data">
{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" name = "submit">提交</button>
</form>
</section>
{% endblock %}